[tasks.review]
workspace = false
install_crate = "cargo-insta"
command = "cargo"
args = [
    "insta",
    "review"
]

[tasks.snapshot]
workspace = false
install_crate = "cargo-insta"
command = "cargo"
args = [
    "insta",
    "test",
    "--delete-unreferenced-snapshots"
]
